// Generated by CoffeeScript 1.3.3
(function() {
  var Snockets, app, db, express, http, mysql, routes, snockets, user;

  console.log("Initializing: " + (new Date));

  routes = require('./routes');

  mysql = require('mysql');

  express = require('express');

  db = require('./common/db.js');

  user = require('./models/user.js');

  http = require('http');

  Snockets = require('snockets');

  snockets = new Snockets();

  snockets.scan(__dirname + '/public/assets/javascripts/mobile.coffee', function(err, depGraph) {
    if (err) {
      return console.warn(err);
    }
  });

  snockets.scan(__dirname + '/public/assets/javascripts/mobile_vendor.coffee', function(err, depGraph) {
    if (err) {
      return console.warn(err);
    }
  });

  app = express();

  app.configure(function() {
    app.set('port', 1337);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(require('stylus').middleware({
      src: __dirname + '/public'
    }));
    app.use(app.router);
    return app.use(express["static"](__dirname + '/public'));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', routes.index);

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + (app.get('port')));
  });

}).call(this);
